import { useState, useEffect, useRef, useCallback } from 'react';

/**
 * A reusable hook to manage algorithm playback state.
 * Consumes the timeline generated by VisualizerAPI and provides playback controls.
 * 
 * @param {Array} snapshots - The timeline generated by VisualizerAPI.getTimeline()
 * @param {number} defaultSpeed - Playback delay in milliseconds
 */
export function useAnimationEngine(snapshots = [], defaultSpeed = 500) {
  const [currentStep, setCurrentStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [playbackSpeed, setPlaybackSpeed] = useState(defaultSpeed);
  
  const totalSteps = snapshots.length;
  const timerRef = useRef(null);

  // Stop playback instantly
  const pause = useCallback(() => {
    setIsPlaying(false);
    if (timerRef.current) clearTimeout(timerRef.current);
  }, []);

  // Play or restart
  const play = useCallback(() => {
    if (totalSteps === 0) return;
    if (currentStep >= totalSteps - 1) {
      setCurrentStep(0); 
    }
    setIsPlaying(true);
  }, [currentStep, totalSteps]);

  // Step Forward (Undo auto-pause)
  const nextStep = useCallback(() => {
    pause();
    setCurrentStep((prev) => Math.min(prev + 1, totalSteps - 1));
  }, [pause, totalSteps]);

  // Step Backward (Undo)
  const prevStep = useCallback(() => {
    pause();
    setCurrentStep((prev) => Math.max(prev - 1, 0));
  }, [pause]);

  // Reset to start
  const reset = useCallback(() => {
    pause();
    setCurrentStep(0);
  }, [pause]);

  // Jump to specific point in timeline
  const jumpToStep = useCallback((step) => {
    pause();
    setCurrentStep(Math.max(0, Math.min(step, totalSteps - 1)));
  }, [pause, totalSteps]);

  // The engine tick loop
  useEffect(() => {
    if (isPlaying && currentStep < totalSteps - 1) {
      timerRef.current = setTimeout(() => {
        setCurrentStep((prev) => prev + 1);
      }, playbackSpeed);
    } else if (currentStep >= totalSteps - 1 && isPlaying) {
      // Reached the end
      setIsPlaying(false);
    }

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [isPlaying, currentStep, playbackSpeed, totalSteps]);

  // Sync current step bounds if snapshot list changes dynamically
  useEffect(() => {
    if (totalSteps > 0 && currentStep >= totalSteps) {
      setCurrentStep(totalSteps - 1);
    }
  }, [totalSteps, currentStep]);

  return {
    currentStep,
    totalSteps,
    isPlaying,
    playbackSpeed,
    activeSnapshot: snapshots[currentStep] || null,
    controls: {
      play,
      pause,
      nextStep,
      prevStep,
      reset,
      jumpToStep,
      setPlaybackSpeed
    }
  };
}
