import { useState, useEffect, useRef, useCallback } from 'react';

/**
 * A reusable hook to manage algorithm playback state.
 * Consumes the timeline generated by VisualizerAPI and provides playback controls.
 */
export function useAnimationEngine(snapshots = [], defaultSpeed = 500) {
  const [currentStep, setCurrentStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [playbackSpeed, setPlaybackSpeed] = useState(defaultSpeed);
  
  const totalSteps = snapshots.length;
  const timerRef = useRef(null);

  const pause = useCallback(() => {
    setIsPlaying(false);
    if (timerRef.current) clearTimeout(timerRef.current);
  }, []);

  const play = useCallback(() => {
    if (totalSteps === 0) return;
    if (currentStep >= totalSteps - 1) {
      setCurrentStep(0); 
    }
    setIsPlaying(true);
  }, [currentStep, totalSteps]);

  const nextStep = useCallback(() => {
    pause();
    setCurrentStep((prev) => Math.min(prev + 1, totalSteps - 1));
  }, [pause, totalSteps]);

  const prevStep = useCallback(() => {
    pause();
    setCurrentStep((prev) => Math.max(prev - 1, 0));
  }, [pause]);

  const reset = useCallback(() => {
    pause();
    setCurrentStep(0);
  }, [pause]);

  const jumpToStep = useCallback((step) => {
    pause();
    setCurrentStep(Math.max(0, Math.min(step, totalSteps - 1)));
  }, [pause, totalSteps]);

  // Engine loop
  useEffect(() => {
    if (isPlaying && currentStep < totalSteps - 1) {
      timerRef.current = setTimeout(() => {
        setCurrentStep((prev) => prev + 1);
      }, playbackSpeed);
    } else if (currentStep >= totalSteps - 1 && isPlaying) {
      setIsPlaying(false);
    }
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [isPlaying, currentStep, playbackSpeed, totalSteps]);

  useEffect(() => {
    if (totalSteps > 0 && currentStep >= totalSteps) {
      setCurrentStep(totalSteps - 1);
    }
  }, [totalSteps, currentStep]);

  // Keyboard Shortcuts
  useEffect(() => {
    const handleKeyDown = (e) => {
      // Don't trigger if user is typing in an input
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
      
      switch (e.key) {
        case ' ':
          e.preventDefault();
          setIsPlaying(prev => !prev);
          break;
        case 'ArrowRight':
          e.preventDefault();
          nextStep();
          break;
        case 'ArrowLeft':
          e.preventDefault();
          prevStep();
          break;
        default:
          break;
      }
    };
    
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [nextStep, prevStep]);

  return {
    currentStep,
    totalSteps,
    isPlaying,
    playbackSpeed,
    activeSnapshot: snapshots[currentStep] || null,
    controls: { play, pause, nextStep, prevStep, reset, jumpToStep, setPlaybackSpeed }
  };
}
